
---
title: "Mass Spec Analysis"
author: "mariuss"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    df_print: paged
    code_folding: hide
---


```{r init, message=F, warning=F}

library(DEP)
library(ggplot2)

library(extrafont)
loadfonts(device = "win")
windowsFonts()
library(ggrepel)
library(DESeq2)
library(dplyr)
setwd("C:/Users/mariu/Documents/MSAP")
library(ggplot2)

location <- read.table("location.txt", sep ="\t")
length(location[,1])
location <- location[grep("ucleus",location[,2]),]

proteinGroups <- read.table("proteinGroups_AP.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE, comment.char = "")
experimental_design <- read.table('experiment_settings_AP.txt', header = TRUE, sep = "\t")
color_code = read.table("color_code.txt", sep = "\t", header = TRUE)
#head(LOCATION)


  
```

```
Extract enriched nuclear proteins
```


```{r, message= FALSE}

LOCATION <-location[,1]
#dim(proteinGroups)
#removing of duplicated row values
proteinGroups  <-  proteinGroups[!duplicated(proteinGroups$Protein.IDs), ]
#dim(proteinGroups)
#filtering of reverse matching peptides
proteinGroups  <-  proteinGroups[proteinGroups$Reverse  !=  "+",
         ]
#dim(proteinGroups)
#filtering of contaminants
proteinGroups  <-  proteinGroups[proteinGroups$Potential.contaminant  !=  "+",
         ]
#dim(proteinGroups)
#filtering of proteins identified by site
proteinGroups  <-  proteinGroups[proteinGroups$Only.identified.by.site  !=  "+",
         ]
#dim(proteinGroups)
#filtering of nuclear proteins
proteinGroups  <-  proteinGroups[proteinGroups$Majority.protein.IDs %in% LOCATION,
         ]
#dim(proteinGroups)

#dim(proteinGroups)


data <- proteinGroups
data_unique <- make_unique(data, "Gene.names", "Protein.IDs", delim = ";")
data_unique <- make_unique(data_unique, "Gene.names", "Protein.IDs", delim = ";")
#head(data_unique)
#dim(data_unique)
data_unique %>% group_by(Gene.names) %>% summarize(frequency = n()) %>% 
  arrange(desc(frequency)) %>% filter(frequency > 1)
LFQ_columns <- grep("LFQ.", colnames(data_unique))

#head(data_unique)





data_se <- make_se(data_unique, LFQ_columns, experimental_design)
data_filt <- filter_missval(data_se, thr = 0)


#data_norm <- normalize_vsn(data_filt)
data_norm <-data_filt
data_imp<- impute(data_norm, fun = "man", shift = 2.5, scale = 0.1)
#data_imp<-impute(data_norm, fun = "MinProb", q = 0.01)

data_diff <- test_diff(data_imp , type = "control", control = "fl")

dep <- add_rejections(data_diff, alpha = 0.1, lfc = 1)

rowRanges(dep)


data_results <- get_results(dep)
write.table(data_results, "DEP_results_AP.csv", sep = ";", quote = FALSE, row.names = FALSE)
#dev.off()

```
```
label enriched proteins
```


```{r, message= FALSE}


data_reprocessed <- read.table("DEP_results_reprocessed.csv", sep = ";", header = TRUE)
data_reprocessed <- data.frame(gene = data_reprocessed[,1],log_p = -log10(data_reprocessed[,3]), log2_FD = data_reprocessed[,7]  )
data_reprocessed <- merge(x = data_reprocessed, y = color_code, by = "gene", all.x = TRUE)
data_reprocessed$color[is.na(data_reprocessed$color)] <- as.character("black")
data_reprocessed$name[is.na(data_reprocessed$name)] <- ""
data_reprocessed$name[data_reprocessed$name != '']

data_reprocessed$name[data_reprocessed$log_p > -log10(0.0005) & data_reprocessed$log2_FD <= -(log2(2))] <- data_reprocessed$gene[data_reprocessed$log_p > -log10(0.0005) & data_reprocessed$log2_FD <= -(log2(2))]
data_reprocessed$color[data_reprocessed$name ==""] <- as.character("grey") 
```
## vulcano plot

```{r fig_vulcano, fig.width=6, fig.height=8}

plot <- ggplot(data = data_reprocessed,aes( x= log2_FD, y= log_p))+geom_point(aes(color = I(color)),size = 1, alpha = 1)
plot <- plot + theme_bw()
plot <- plot + geom_hline(yintercept = -log10(0.0005), color = "black", linetype=2, size = 0.5)
plot <- plot + geom_vline(xintercept = (log2(2)), color  = "black", linetype=2, size = 0.5)
plot <- plot + geom_vline(xintercept = -(log2(2)), color  = "black", linetype=2, size = 0.5)
#plot <- plot + geom_vline(xintercept = -(log2(5)), color  = "darkgrey", linetype=2, size = 0.5)
#plot <- plot + geom_vline(xintercept = 0, color  = "black", linetype=2, size = 0.5)
#plot <- plot + geom_vline(xintercept = (log2(2)), color  = "black", linetype=2, size = 0.5)
#plot <- plot + geom_vline(xintercept = (log2(5)), color  = "black", linetype=2, size = 0.5)



plot <- plot  +   geom_text_repel(aes(x= log2_FD, y= log_p,label = name, color = color), max.overlaps = Inf, size =2.5, family = "sans")




plot <- plot + scale_x_continuous(limits = c(-6,6),breaks=seq(-6, 6,4))
#plot <- plot + scale_color_manual(values = c("black","cyan", "orange","red"))
plot <- plot+labs(title="", x= "-log2 (fold change)", y = "-log10 (p-value)")

plot <- plot + theme(axis.title = element_text(size = 8, family = "sans")) 

plot <- plot + theme(text=element_text(size=8 ,family = "sans"), axis.line = element_line(color = "black"), axis.text = element_text(color = "black"))

pdf("vulcanoPlot_labeled_AP.pdf", width = 4, height = 5.3)

plot
dev.off()
plot
```